name: solid_lints_example
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  boolean_lints:
    path: ../
  custom_lint: ^0.5.0
  test: ^1.20.1
