include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:

boolean_lints:
  rules:
    banned_code:
      severity: warning
      entries:
        - class_name: BannedCodeUsage
          id: test
          reason: "BannedCodeUsage.test is not allowed"
