name: id_class
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.4

dependencies:
  custom_lint: ^0.5.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  boolean_lints:
    path: ../../../
