include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:

boolean_lints:
  rules_exclude:
    - ".*excluded\\.dart"
  rules:
    avoid_hardcoded_strings:
      minimum_length: 3
      severity: warning
    banned_code:
      severity: warning
      entries:
        # Ban global id from any package
        # - id: test2
        #   reason: "test methods and variables should not be used"
        #   severity: info


        # - class_name: BannedCodeUsage
        #   package: example
        #   reason: "BannedCodeUsage is not allowed"
        # - id: test2
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test2 is not allowed"
        # - id: test4
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test4 is not allowed"
        # - id: test
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test is not allowed"
        # - package: example
        #   id: test2
        #   reason: Do not use test2 from the example package
        # - package: example
        #   id: test
        #   reason: Do not use test from the example package
        # - package: example
        #   reason: Do not use the example package
        # - id: test
        #   reason: "test methods are not allowed"
        # - id: test2
        #   reason: "test2 methods not allowed"
        # - class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage is not allowed"
        # - class_name: BannedCodeUsage
        #   id: test
        #   reason: "Banned code usage is not allowed"
        #   package: example
        # - class_name: BannedCodeUsage
        #   id: test2
        #   reason: "Banned code usage 2 is not allowed"
        #   package: example
        # - id: test3
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test3 is not allowed"
        # - id: test2
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test2 is not allowed"
        # - id: test
        #   class_name: BannedCodeUsage
        #   reason: "BannedCodeUsage.test is not allowed"
        # - id: test3
        #   class_name: BannedCodeUsage
        #   package: example
        #   reason: "BannedCodeUsage.test3 from the example package is not allowed"
        # - id: test2
        #   class_name: BannedCodeUsage
        #   package: example
        #   reason: "BannedCodeUsage.test2 from the example package is not allowed"
        # - id: test
        #   class_name: BannedCodeUsage
        #   package: example
        #   reason: "BannedCodeUsage.test from the example package is not allowed"
