include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:

boolean_lints:
  rules:
    banned_code:
      severity: warning
      entries:
        - id: test
          reason: "Global test methods/variables should not be used"
